export const ipcChannels = {
  projectCreate: "project:create",
  projectList: "project:list",
  projectUpdate: "project:update",
  projectDelete: "project:delete",
  projectOpen: "project:open",
  chapterCreate: "chapter:create",
  chapterUpdate: "chapter:update",
  chapterList: "chapter:list",
  chapterRead: "chapter:read",
  chapterDelete: "chapter:delete",
  chapterReorder: "chapter:reorder",
  chapterImportMd: "chapter:import-md",
  chapterExportMd: "chapter:export-md",
  chapterAutosaveWrite: "chapter:autosave-write",
  chapterAutosavePeek: "chapter:autosave-peek",
  chapterAutosaveClear: "chapter:autosave-clear",
  providerSave: "provider:save",
  providerList: "provider:list",
  providerDelete: "provider:delete",
  providerTest: "provider:test",
  llmAnalyze: "llm:analyze",
  llmQuick: "llm:quick",
  llmChat: "llm:chat",
  feedbackList: "feedback:list",
  feedbackDismiss: "feedback:dismiss",
  feedbackDeleteEmpty: "feedback:delete-empty",
  feedbackClearChapter: "feedback:clear-chapter",
  outlineCreate: "outline:create",
  outlineUpdate: "outline:update",
  outlineDelete: "outline:delete",
  outlineList: "outline:list",
  dailyProgress: "daily:progress",
  settingsGet: "settings:get",
  settingsSet: "settings:set",
  externalOpenUrl: "external:open-url",
  fsPickFile: "fs:pick-file",
  fsSaveFile: "fs:save-file",
  terminalSpawn: "terminal:spawn",
  terminalInput: "terminal:input",
  terminalResize: "terminal:resize",
  terminalDispose: "terminal:dispose",
  skillCreate: "skill:create",
  skillUpdate: "skill:update",
  skillGet: "skill:get",
  skillList: "skill:list",
  skillDelete: "skill:delete",
  skillRun: "skill:run",
  skillImportJson: "skill:import-json",
  skillExportJson: "skill:export-json",
  tavernCardCreate: "tavern-card:create",
  tavernCardUpdate: "tavern-card:update",
  tavernCardGet: "tavern-card:get",
  tavernCardList: "tavern-card:list",
  tavernCardDelete: "tavern-card:delete",
  novelCharacterCreate: "novel-character:create",
  novelCharacterUpdate: "novel-character:update",
  novelCharacterGet: "novel-character:get",
  novelCharacterList: "novel-character:list",
  novelCharacterDelete: "novel-character:delete",
  novelCharacterExtractFromChapter: "novel-character:extract-from-chapter",
  novelCharacterImportCandidates: "novel-character:import-candidates",
  characterSyncPreview: "character-sync:preview",
  characterSyncApply: "character-sync:apply",
  characterSyncHistory: "character-sync:history",
  tavernSessionCreate: "tavern-session:create",
  tavernSessionGet: "tavern-session:get",
  tavernSessionList: "tavern-session:list",
  tavernSessionDelete: "tavern-session:delete",
  tavernMessageList: "tavern-message:list",
  tavernDirectorPost: "tavern-director:post",
  tavernRoundRun: "tavern-round:run",
  tavernRoundStop: "tavern-round:stop",
  tavernSummaryCompact: "tavern-summary:compact",
  worldList: "world:list",
  worldGet: "world:get",
  worldCreate: "world:create",
  worldUpdate: "world:update",
  worldDelete: "world:delete",
  worldSearch: "world:search",
  researchSearch: "research:search",
  researchList: "research:list",
  researchGet: "research:get",
  researchSave: "research:save",
  researchUpdate: "research:update",
  researchDelete: "research:delete",
  researchCredentialStatus: "research:credential-status",
  researchCredentialUpsert: "research:credential-upsert",
  researchCredentialDelete: "research:credential-delete",
  reviewDimList: "review-dim:list",
  reviewDimUpsert: "review-dim:upsert",
  reviewDimDelete: "review-dim:delete",
  reviewDimReorder: "review-dim:reorder",
  reviewRun: "review:run",
  reviewCancel: "review:cancel",
  reviewList: "review:list",
  reviewGet: "review:get",
  reviewDismissFinding: "review:dismiss-finding",
  reviewExport: "review:export",
  reviewApplyFix: "review:apply-fix",
  dailySummaryGenerate: "daily:summary-generate",
  dailySummaryGet: "daily:summary-get",
  dailySummaryList: "daily:summary-list",
  providerKeyList: "provider-key:list",
  providerKeyUpsert: "provider-key:upsert",
  providerKeyDelete: "provider-key:delete",
  providerKeySetDisabled: "provider-key:set-disabled",
  providerKeyHealth: "provider-key:health",
  diagSnapshot: "diag:snapshot",
  diagCrashStatus: "diag:crash-status",
  diagCrashDismiss: "diag:crash-dismiss",
  updateCheck: "update:check",
  updateDownload: "update:download",
  updateInstall: "update:install",
  updateStatus: "update:get-status",
  updateOpenDownloadPage: "update:open-download-page",
  marketFetchRegistry: "market:fetch-registry",
  marketInstallSkill: "market:install-skill",
  marketBuildPublishBundle: "market:build-publish-bundle",
  // ===== M7 · Bookshelf =====
  bookshelfListBooks: "bookshelf:list-books",
  bookCoverUpload: "book-cover:upload",
  bookCoverGet: "book-cover:get",
  bookCoverDelete: "book-cover:delete",
  // ----- Origin Tag -----
  originTagSet: "origin-tag:set",
  originTagGet: "origin-tag:get",
  originTagListByOrigin: "origin-tag:list-by-origin",
  // ----- Chapter Log -----
  chapterLogList: "chapter-log:list",
  chapterLogAppendManual: "chapter-log:append-manual",
  chapterLogAppendAi: "chapter-log:append-ai",
  chapterLogDelete: "chapter-log:delete",
  // ----- Auto Writer -----
  autoWriterStart: "auto-writer:start",
  autoWriterStop: "auto-writer:stop",
  autoWriterPause: "auto-writer:pause",
  autoWriterResume: "auto-writer:resume",
  autoWriterGetRun: "auto-writer:get-run",
  autoWriterListRuns: "auto-writer:list-runs",
  autoWriterInjectIdea: "auto-writer:inject-idea",
  autoWriterCorrect: "auto-writer:correct",
  // ----- Snapshot -----
  snapshotCreate: "snapshot:create",
  snapshotList: "snapshot:list",
  snapshotGet: "snapshot:get",
  snapshotRestore: "snapshot:restore",
  snapshotDelete: "snapshot:delete",
  // ----- Window 控制（自定义 titlebar 用） -----
  windowMinimize: "window:minimize",
  windowToggleMaximize: "window:toggle-maximize",
  windowClose: "window:close",
  windowIsMaximized: "window:is-maximized",
  // ----- M8 · 活人感（Achievements + Letters） -----
  achievementList: "achievement:list",
  achievementCheck: "achievement:check",
  achievementStats: "achievement:stats",
  letterList: "letter:list",
  letterGenerate: "letter:generate",
  letterMarkRead: "letter:mark-read",
  letterPin: "letter:pin",
  letterDismiss: "letter:dismiss",
  letterDelete: "letter:delete",
  // ----- Scene Bindings (ported from ainovel) -----
  sceneBindingList: "scene-binding:list",
  sceneBindingUpsert: "scene-binding:upsert",
  sceneBindingReset: "scene-binding:reset",
  sceneBindingGetMode: "scene-binding:get-mode",
  sceneBindingSetMode: "scene-binding:set-mode",
  // ----- Sample Library (参考小说库, ported from ainovel) -----
  sampleLibList: "sample-lib:list",
  sampleLibCreate: "sample-lib:create",
  sampleLibDelete: "sample-lib:delete",
  sampleLibImportText: "sample-lib:import-text",
  sampleLibImportEpub: "sample-lib:import-epub",
  // ----- World Relationships (graph, ported from ainovel) -----
  worldRelationshipList: "world-relationship:list",
  worldRelationshipSave: "world-relationship:save",
  worldRelationshipDelete: "world-relationship:delete",
  // ----- Project Export + Chapter Bulk Import (ported from ainovel) -----
  projectExportTxt: "project:export-txt",
  projectExportMd: "project:export-md",
  projectExportHtml: "project:export-html",
  projectExportDocx: "project:export-docx",
  projectExportEpub: "project:export-epub",
  chapterImportTxt: "chapter:import-txt",
  chapterImportEpub: "chapter:import-epub",
  // ----- Module 6: AI outline + chapter generation (ainovel-style chained) -----
  projectUpdateMeta: "project:update-meta",
  outlineGenerateMaster: "outline:generate-master",
  outlineGenerateChapters: "outline:generate-chapters",
  outlineRefine: "outline:refine",
  outlineUndoRefine: "outline:undo-refine",
  chapterGenerateFromOutline: "chapter:generate-from-outline",
  // ----- v20: Materials (独立顶级素材库) -----
  materialList: "material:list",
  materialCreate: "material:create",
  materialUpdate: "material:update",
  materialDelete: "material:delete",
  chapterCommitDraft: "chapter:commit-draft",
  // ----- Provider remote model list (ainovel-style discovery) -----
  providerListRemoteModels: "provider:list-remote-models",
  // ----- v23: Worldview Cards -----
  worldPackList: "world-pack:list",
  worldPackGet: "world-pack:get",
  worldPackCreate: "world-pack:create",
  worldPackUpdate: "world-pack:update",
  worldPackDelete: "world-pack:delete",
  worldPackEntryList: "world-pack:entry-list",
  worldPackEntryCreate: "world-pack:entry-create",
  worldPackEntryUpdate: "world-pack:entry-update",
  worldPackEntryDelete: "world-pack:entry-delete",
  worldPackSlotList: "world-pack:slot-list",
  worldPackSlotAdd: "world-pack:slot-add",
  worldPackSlotRemove: "world-pack:slot-remove",
  worldPackSlotToggle: "world-pack:slot-toggle",
  worldPackSlotReorder: "world-pack:slot-reorder",
  worldPackCoverWrite: "world-pack:cover-write",
  worldPackCoverRead: "world-pack:cover-read",
  worldPackFuse: "world-pack:fuse",
  // ----- v24: Author's Note -----
  authorNoteGet: "author-note:get",
  authorNoteUpsert: "author-note:upsert",
  authorNoteDelete: "author-note:delete",
  // ----- v25: Character Card (CCv3) import / export -----
  characterCardImport: "character-card:import",
  characterCardExport: "character-card:export",
  characterCardListImports: "character-card:list-imports",
  // ----- v26: Voice Profile -----
  voiceProfileGet: "voice-profile:get",
  voiceProfileUpsert: "voice-profile:upsert",
  voiceProfileSetEnabled: "voice-profile:set-enabled",
  voiceProfileDelete: "voice-profile:delete",
  // ----- v26: World Info Trace -----
  worldInfoTraceListRecent: "world-info-trace:list-recent",
  worldInfoTraceGet: "world-info-trace:get",
  worldInfoTraceClear: "world-info-trace:clear",
} as const;

export const ipcEventChannels = {
  llmChunk: "llm:chunk",
  llmDone: "llm:done",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
  skillChunk: "skill:chunk",
  skillDone: "skill:done",
  tavernChunk: "tavern:chunk",
  tavernDone: "tavern:done",
  tavernBudgetWarning: "tavern:budget-warning",
  reviewProgress: "review:progress",
  reviewDone: "review:done",
  dailySummaryChunk: "daily:summary-chunk",
  dailySummaryDone: "daily:summary-done",
  updateStatus: "update:status",
  // ===== M7 · Bookshelf =====
  autoWriterChunk: "auto-writer:chunk",
  autoWriterPhase: "auto-writer:phase",
  autoWriterDone: "auto-writer:done",
  autoWriterSnapshot: "auto-writer:snapshot",
  chapterLogReminder: "chapter-log:daily-reminder",
  windowMaximizedChanged: "window:maximized-changed",
  // ----- M8 · 活人感 -----
  achievementUnlocked: "achievement:unlocked",
  letterArrived: "letter:arrived",
} as const;
